# Version du format Docker Compose
version: '3.8'

# Définition des services à lancer
services:
  # Service MongoDB (base de données principale)
  mongodb:
    image: mongo:latest                       # Utilise l'image officielle MongoDB (dernière version)
    container_name: questionnaire-mongodb    # Nom du conteneur pour identification facile
    ports:
      - "27017:27017"                        # Map le port 27017 du conteneur au port 27017 de la machine locale
    environment:
      MONGO_INITDB_DATABASE: questionnaire_db  # Nom de la base créée automatiquement à l'initialisation
    volumes:
      - mongodb_data:/data/db                # Volume pour persister les données de la base
      - mongodb_config:/data/configdb        # Volume pour persister les fichiers de configuration de MongoDB
    restart: unless-stopped                   # Redémarre automatiquement le conteneur sauf si tu l'arrêtes manuellement
    healthcheck:                              # Vérification de l'état du conteneur
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/questionnaire_db --quiet
      interval: 10s                           # Vérifie toutes les 10 secondes
      timeout: 5s                             # Timeout après 5 secondes
      retries: 5                              # Nombre de tentatives avant de considérer le conteneur comme "non sain"

  # Service optionnel : Mongo Express (interface web pour MongoDB)
  mongo-express:
    image: mongo-express:latest               # Image officielle Mongo Express
    container_name: questionnaire-mongo-express
    ports:
      - "8081:8081"                           # Accessible via navigateur sur le port 8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/   # URL de connexion vers MongoDB (nom du service = mongodb)
      ME_CONFIG_BASICAUTH_USERNAME: admin                # Utilisateur admin pour Mongo Express
      ME_CONFIG_BASICAUTH_PASSWORD: admin123            # Mot de passe admin pour Mongo Express
    depends_on:
      - mongodb                               # Assure que MongoDB est lancé avant Mongo Express
    restart: unless-stopped                    # Redémarrage automatique comme MongoDB

# Définition des volumes Docker pour persistance
volumes:
  mongodb_data:                               # Volume pour stocker les données
    driver: local
  mongodb_config:                             # Volume pour stocker la configuration
    driver: local
